destination: production
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  smart_quotes: ["apos", "apos", "quot", "quot"]
paginate: 10
highlighter: pygments

gitrepo: "https://github.com/ucf-cs/tervel"