destination: production
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  smart_quotes: ["apos", "apos", "quot", "quot"]
paginate: 10
highlighter: pygments

myurl: "http://ucf-cs.github.io/Tervel"
gitrepo: "https://github.com/ucf-cs/tervel"

